import BaseSeeder from '@ioc:Adonis/Lucid/Seeder'
import Club from 'App/Models/Club'

export default class ClubSeeder extends BaseSeeder {
  public async run () {
    //make data 100 club
    const clubs = [
      {
        full_name: 'Arsenal',
        short_name: 'Arsenal',
        country: 'England',
        city: 'London',
        slug: 'arsenal',
        logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/5/53/Arsenal_FC.svg/1200px-Arsenal_FC.svg.png',
        stadium: 'Emirates Stadium',
        stadium_capacity: 60361,
        stadium_location: 'London',
        stadium_description:'-',
        stadium_image: 'https://upload.wikimedia.org/wikipedia/en/thumb/5/53/Arsenal_FC.svg/1200px-Arsenal_FC.svg.png',
        fans_name: 'The Gunners',
      },
      {
        full_name: 'Aston Villa',
        short_name: 'Aston Villa',
        country: 'England',
        city: 'Birmingham',
        slug: 'aston-villa',
        logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/b/b1/Aston_Villa_logo.svg/1200px-Aston_Villa_logo.svg.png',
        stadium: 'Villa Park',
        stadium_capacity: 50000,
        stadium_location: 'Birmingham',
        stadium_description:'-',
        stadium_image: 'https://upload.wikimedia.org/wikipedia/en/thumb/b/b1/Aston_Villa_logo.svg/1200px-Aston_Villa_logo.svg.png',
        fans_name: 'The Villans',
      },
      {
        full_name: 'Chelsea',
        short_name: 'Chelsea',
        country: 'England',
        city: 'London',
        slug: 'chelsea',
        logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/5/5c/Chelsea_crest.svg/1200px-Chelsea_crest.svg.png',
        stadium: 'Stamford Bridge',
        stadium_capacity: 50000,
        stadium_location: 'London',
        stadium_description:'-',
        stadium_image: 'https://upload.wikimedia.org/wikipedia/en/thumb/5/5c/Chelsea_crest.svg/1200px-Chelsea_crest.svg.png',
        fans_name: 'The Blues',
      },
      {
        full_name: 'Crystal Palace',
        short_name: 'Crystal Palace',
        country: 'England',
        city: 'London',
        slug: 'crystal-palace',
        logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/6/6f/Crystal_Palace_FC_logo.svg/1200px-Crystal_Palace_FC_logo.svg.png',
        stadium: 'Selhurst Park',
        stadium_capacity: 50000,
        stadium_location: 'London',
        stadium_description:'-',
        stadium_image: 'https://upload.wikimedia.org/wikipedia/en/thumb/6/6f/Crystal_Palace_FC_logo.svg/1200px-Crystal_Palace_FC_logo.svg.png',
        fans_name: 'The Kings',
      },
      {
        full_name: 'Everton',
        short_name: 'Everton',
        country: 'England',
        city: 'Liverpool',
        slug: 'everton',
        logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/d/d1/Everton_FC.svg/1200px-Everton_FC.svg.png',
        stadium: 'Goodison Park',
        stadium_capacity: 50000,
        stadium_location: 'Liverpool',
        stadium_description:'-',
        stadium_image: 'https://upload.wikimedia.org/wikipedia/en/thumb/d/d1/Everton_FC.svg/1200px-Everton_FC.svg.png',
        fans_name: 'The Toffees',
      },
      {
        full_name: 'Leicester City',
        short_name: 'Leicester City',
        country: 'England',
        city: 'Leicester',
        slug: 'leicester-city',
        logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/b/b7/Leicester_City_crest.svg/1200px-Leicester_City_crest.svg.png',
        stadium: 'King Power Stadium',
        stadium_capacity: 50000,
        stadium_location: 'Leicester',
        stadium_description:'-',
        stadium_image: 'https://upload.wikimedia.org/wikipedia/en/thumb/b/b7/Leicester_City_crest.svg/1200px-Leicester_City_crest.svg.png',
        fans_name: 'The Foxes',
      },
      {
        full_name: 'Liverpool',
        short_name: 'Liverpool',
        country: 'England',
        city: 'Liverpool',
        slug: 'liverpool',
        logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/0/0a/Liverpool_FC.svg/1200px-Liverpool_FC.svg.png',
        stadium: 'Anfield',
        stadium_capacity: 50000,
        stadium_location: 'Liverpool',
        stadium_description:'-',
        stadium_image: 'https://upload.wikimedia.org/wikipedia/en/thumb/0/0a/Liverpool_FC.svg/1200px-Liverpool_FC.svg.png',
        fans_name: 'The Reds',
      },
      {
        full_name: 'Manchester City',
        short_name: 'Manchester City',
        country: 'England',
        city: 'Manchester',
        slug: 'manchester-city',
        logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/e/eb/Manchester_City_FC_badge.svg/1200px-Manchester_City_FC_badge.svg.png',
        stadium: 'Etihad Stadium',
        stadium_capacity: 50000,
        stadium_location: 'Manchester',
        stadium_description:'-',
        stadium_image: 'https://upload.wikimedia.org/wikipedia/en/thumb/e/eb/Manchester_City_FC_badge.svg/1200px-Manchester_City_FC_badge.svg.png',
        fans_name: 'The City',
      },
      {
        full_name: 'Manchester United',
        short_name: 'Manchester United',
        country: 'England',
        city: 'Manchester',
        slug: 'manchester-united',
        logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/0/0d/Manchester_United_FC_crest.svg/1200px-Manchester_United_FC_crest.svg.png',
        stadium: 'Old Trafford',
        stadium_capacity: 50000,
        stadium_location: 'Manchester',
        stadium_description:'-',
        stadium_image: 'https://upload.wikimedia.org/wikipedia/en/thumb/0/0d/Manchester_United_FC_crest.svg/1200px-Manchester_United_FC_crest.svg.png',
        fans_name: 'The United',
      },
      {
        full_name: 'Newcastle United',
        short_name: 'Newcastle United',
        country: 'England',
        city: 'Newcastle',
        slug: 'newcastle-united',
        logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/d/d2/Newcastle_United_Logo.svg/1200px-Newcastle_United_Logo.svg.png',
        stadium: 'St. James\' Park',
        stadium_capacity: 50000,
        stadium_location: 'Newcastle',
        stadium_description:'-',
        stadium_image: 'https://upload.wikimedia.org/wikipedia/en/thumb/d/d2/Newcastle_United_Logo.svg/1200px-Newcastle_United_Logo.svg.png',
        fans_name: 'The Whites',
      },
      {
        full_name: 'Southampton',
        short_name: 'Southampton',
        country: 'England',
        city: 'Southampton',
        slug: 'southampton',
        logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/a/aa/FC_Southampton.svg/1200px-FC_Southampton.svg.png',
        stadium: 'St. Mary\'s Stadium',
        stadium_capacity: 50000,
        stadium_location: 'Southampton',
        stadium_description:'-',
        stadium_image: 'https://upload.wikimedia.org/wikipedia/en/thumb/a/aa/FC_Southampton.svg/1200px-FC_Southampton.svg.png',
        fans_name: 'The Saints',
      }
    ]

    await Club.createMany(clubs)

  }
}
